spring.application.name=consultation

spring.datasource.url=jdbc:mysql://localhost:3306/consultation_db
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

ollama.model=qwen2.5:3b

whisper.exe-path=C:/ai/whisper.cpp/Release/whisper-cli.exe
whisper.model-path=C:/ai/whisper.cpp/models/ggml-base.bin
whisper.language=ko